import type { SpriteDef } from './sprites';

export interface SnackItem {
  id: string;
  name: string;
  type: 'energy-drink' | 'soda' | 'chips' | 'candy';
  /** Big sprite shown on the vending shelf (24w x 32h grid) */
  spriteShelf: SpriteDef;
  /** Small sprite shown in character's hand (10w x 14h grid) */
  spriteHandheld: SpriteDef;
  /** Accent color for the modal card border / glow */
  accentColor: string;
  /** Short flavor text shown in the modal when item is hovered */
  flavor: string;
  /** Whether this is eaten ('eat') or drunk ('drink') — drives animation */
  action: 'eat' | 'drink';
}

// ===========================================================================
// SPRITE PALETTE & DESIGN NOTES
// ===========================================================================
// All shelf sprites are 24 wide x 32 tall. All handheld sprites are 10 x 14.
// The Sprite renderer (components/icons/Sprite.tsx) treats each character of
// each row as a single pixel — characters not present in the palette become
// transparent. We therefore use ONLY well-defined palette keys (no
// accidental words inside row strings). The shapes themselves communicate
// the brand: tall cans (energy + soda), chip bags (crinkled top + wider top),
// candy bars (horizontal wrapper with crimped ends).
// ===========================================================================

// === 1. BEAST RAGE — dark green energy can, black/yellow snarl =============
const BEAST_SHELF: SpriteDef = {
  id: 'beast-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009', // outline
    W: '#f5e8ff', // highlight
    S: '#1a3a14', // shadow
    G: '#0a4a18', // dark green body
    g: '#1e7530', // mid green
    L: '#39ff14', // bright green
    Y: '#ffe600', // yellow snarl
    B: '#000000', // black mouth
  },
  rows: [
    '........KKKKKKKK........',
    '........KSSSSSSK........',
    '.......KSSSSSSSSK.......',
    '.......KSKKKKKKSK.......',
    '......KGGGGGGGGGGK......',
    '......KGggggggggGK......',
    '......KGgWWWWWWgGK......',
    '......KGgWLLLLWgGK......',
    '......KGgWLKKLWgGK......',
    '......KGgWLLLLWgGK......',
    '......KGgWWWWWWgGK......',
    '......KGgggggggGK.......',
    '......KGgKKKKKKgGK......',
    '......KGYBBBBBBYgGK.....',
    '......KGYBYYYYBYgGK.....',
    '......KGYBYKKYBYgGK.....',
    '......KGYBYKKYBYgGK.....',
    '......KGYBYYYYBYgGK.....',
    '......KGYBBBBBBYgGK.....',
    '......KGgKKKKKKgGK......',
    '......KGggggggggGK......',
    '......KGgLLLLLLLgGK.....',
    '......KGgLKKKKKLgGK.....',
    '......KGgLKLLLKLgGK.....',
    '......KGgLKKKKKLgGK.....',
    '......KGgLLLLLLLgGK.....',
    '......KGggggggggGK......',
    '......KGGGGGGGGGGK......',
    '......KKKKKKKKKKKK......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........SSSSSSSS........',
  ],
};

const BEAST_HAND: SpriteDef = {
  id: 'beast-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#1a3a14',
    G: '#0a4a18',
    g: '#1e7530',
    Y: '#ffe600',
    B: '#000000',
    L: '#39ff14',
  },
  rows: [
    '..KKKKKK..',
    '..KSSSSK..',
    '..KGGGGK..',
    '.KGggggGK.',
    '.KGYBBYGK.',
    '.KGYBBYGK.',
    '.KGggggGK.',
    '.KGgLLgGK.',
    '.KGgLLgGK.',
    '.KGggggGK.',
    '.KGGGGGGK.',
    '.KKKKKKKK.',
    '..SSSSSS..',
    '..KKKKKK..',
  ],
};

// === 2. VOLT — electric blue can w/ chunky yellow lightning bolt ===========
const VOLT_SHELF: SpriteDef = {
  id: 'volt-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#0a2a44',
    B: '#0a4a78', // dark blue
    b: '#00f0ff', // bright cyan
    Y: '#ffe600',
  },
  rows: [
    '........KKKKKKKK........',
    '........KSSSSSSK........',
    '.......KSSSSSSSSK.......',
    '.......KSKKKKKKSK.......',
    '......KBBBBBBBBBBK......',
    '......KBbbbbbbbbBK......',
    '......KBbWWWWWWbBK......',
    '......KBbWbbbbWbBK......',
    '......KBbWbKKbWbBK......',
    '......KBbWbbbbWbBK......',
    '......KBbWWWWWWbBK......',
    '......KBbbbbbbbBK.......',
    '......KBbbbbYYbbBK......',
    '......KBbbbYYYbbBK......',
    '......KBbbYYYbbbBK......',
    '......KBbYYYYYYbBK......',
    '......KBbbbbYYYbBK......',
    '......KBbbbYYYbbBK......',
    '......KBbbYYYbbbBK......',
    '......KBbYYbbbbbBK......',
    '......KBbbbbbbbBK.......',
    '......KBbWWWWWWbBK......',
    '......KBbWYbYbYWbBK.....',
    '......KBbWWWWWWbBK......',
    '......KBbbbbbbbBK.......',
    '......KBBBBBBBBBBK......',
    '......KKKKKKKKKKKK......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........SSSSSSSS........',
    '........SSSSSSSS........',
    '........KKKKKKKK........',
  ],
};

const VOLT_HAND: SpriteDef = {
  id: 'volt-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#0a2a44',
    B: '#0a4a78',
    b: '#00f0ff',
    Y: '#ffe600',
  },
  rows: [
    '..KKKKKK..',
    '..KSSSSK..',
    '..KBBBBK..',
    '.KBbbbbBK.',
    '.KBbYYbBK.',
    '.KBYYYbBK.',
    '.KBYYbbBK.',
    '.KBbYYYBK.',
    '.KBbbYYBK.',
    '.KBbYYbBK.',
    '.KBbbbbBK.',
    '.KBBBBBBK.',
    '.KKKKKKKK.',
    '..SSSSSS..',
  ],
};

// === 3. RIOT — red/black can w/ white fist =================================
const RIOT_SHELF: SpriteDef = {
  id: 'riot-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#2a0408',
    R: '#a8081a', // dark red
    r: '#ff2030', // bright red
    B: '#000000',
  },
  rows: [
    '........KKKKKKKK........',
    '........KSSSSSSK........',
    '.......KSSSSSSSSK.......',
    '.......KSKKKKKKSK.......',
    '......KBBBBBBBBBBK......',
    '......KBRRRRRRRRBK......',
    '......KBRrrrrrrRBK......',
    '......KBRrWWWWrRBK......',
    '......KBRrWrrWrRBK......',
    '......KBRrWWWWrRBK......',
    '......KBRrrrrrrRBK......',
    '......KBRrrrWWrrRBK.....',
    '......KBRrrWWWWrRBK.....',
    '......KBRrWWWWWWrRBK....',
    '......KBRrWWBWWWWrRBK...',
    '......KBRrWBBBWWWrRBK...',
    '......KBRrWBWBWWWrRBK...',
    '......KBRrWWWWWWWrRBK...',
    '......KBRrrWWWWWrrRBK...',
    '......KBRrrrWWWrrrRBK...',
    '......KBRrrrrWWrrrRBK...',
    '......KBRrrrrrrrrRBK....',
    '......KBRrrrrrrrRBK.....',
    '......KBRrrrrrrRBK......',
    '......KBRRRRRRRRBK......',
    '......KBBBBBBBBBBK......',
    '......KKKKKKKKKKKK......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........SSSSSSSS........',
    '........SSSSSSSS........',
    '........KKKKKKKK........',
  ],
};

const RIOT_HAND: SpriteDef = {
  id: 'riot-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#2a0408',
    B: '#000000',
    R: '#a8081a',
    r: '#ff2030',
    W: '#f5e8ff',
  },
  rows: [
    '..KKKKKK..',
    '..KSSSSK..',
    '..KBBBBK..',
    '.KBRRRRBK.',
    '.KBRrrRBK.',
    '.KBRWWRBK.',
    '.KBWBWWBK.',
    '.KBWWWWBK.',
    '.KBRWWRBK.',
    '.KBRrrRBK.',
    '.KBRRRRBK.',
    '.KBBBBBBK.',
    '.KKKKKKKK.',
    '..SSSSSS..',
  ],
};

// === 4. ZAP — purple can w/ swirling pixel vortex ==========================
const ZAP_SHELF: SpriteDef = {
  id: 'zap-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#2a0e4a',
    P: '#3a106a', // dark purple
    p: '#a85cff', // bright purple
    L: '#d4a8ff', // light purple
  },
  rows: [
    '........KKKKKKKK........',
    '........KSSSSSSK........',
    '.......KSSSSSSSSK.......',
    '.......KSKKKKKKSK.......',
    '......KPPPPPPPPPPK......',
    '......KPppppppppPK......',
    '......KPpWWWWWWpPK......',
    '......KPpWpppppWpPK.....',
    '......KPpWpKKKpWpPK.....',
    '......KPpWpppppWpPK.....',
    '......KPpWWWWWWpPK......',
    '......KPpppppppPK.......',
    '......KPpLLLLLLLpPK.....',
    '......KPpLpppppLpPK.....',
    '......KPpLpKKKKLpPK.....',
    '......KPpLpKLLLLpPK.....',
    '......KPpLpKLpKLpPK.....',
    '......KPpLpKLLKLpPK.....',
    '......KPpLpKKKpLpPK.....',
    '......KPpLppppLLpPK.....',
    '......KPpLLLLLLLpPK.....',
    '......KPpppppppPK.......',
    '......KPpWWWWWWpPK......',
    '......KPpWLLpLLWpPK.....',
    '......KPpWpLLLLpWpPK....',
    '......KPpWWWWWWpPK......',
    '......KPppppppppPK......',
    '......KPPPPPPPPPPK......',
    '......KKKKKKKKKKKK......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........SSSSSSSS........',
  ],
};

const ZAP_HAND: SpriteDef = {
  id: 'zap-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#2a0e4a',
    P: '#3a106a',
    p: '#a85cff',
    L: '#d4a8ff',
  },
  rows: [
    '..KKKKKK..',
    '..KSSSSK..',
    '..KPPPPK..',
    '.KPppppPK.',
    '.KPpLLpPK.',
    '.KPLpKLPK.',
    '.KPLKLLPK.',
    '.KPLLKLPK.',
    '.KPLLLpPK.',
    '.KPpLLpPK.',
    '.KPppppPK.',
    '.KPPPPPPK.',
    '.KKKKKKKK.',
    '..SSSSSS..',
  ],
};

// === 5. POP COLA — red can w/ white horizontal band ========================
// Shorter can: starts on row 2.
const POPCOLA_SHELF: SpriteDef = {
  id: 'popcola-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#2a0408',
    R: '#c2122a', // dark red
    r: '#ff4655', // bright red
  },
  rows: [
    '........................',
    '........................',
    '........KKKKKKKK........',
    '........KSSSSSSK........',
    '.......KSSSSSSSSK.......',
    '.......KSKKKKKKSK.......',
    '......KRRRRRRRRRRK......',
    '......KRrrrrrrrrRK......',
    '......KRrrrrrrrrRK......',
    '......KRrrrrrrrrRK......',
    '......KWWWWWWWWWWK......',
    '......KWKWKWKWKWWK......',
    '......KWWKWKWKWWWK......',
    '......KWKWKWKWKWWK......',
    '......KWWWWWWWWWWK......',
    '......KRrrrrrrrrRK......',
    '......KRrWWWWWWrRK......',
    '......KRrWRRRRWrRK......',
    '......KRrWRrrRWrRK......',
    '......KRrWRRRRWrRK......',
    '......KRrWWWWWWrRK......',
    '......KRrrrrrrrrRK......',
    '......KRRRRRRRRRRK......',
    '......KKKKKKKKKKKK......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........SSSSSSSS........',
    '........SSSSSSSS........',
    '........KKKKKKKK........',
    '........................',
    '........................',
    '........................',
  ],
};

const POPCOLA_HAND: SpriteDef = {
  id: 'popcola-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#2a0408',
    R: '#c2122a',
    r: '#ff4655',
    W: '#f5e8ff',
  },
  rows: [
    '..........',
    '..KKKKKK..',
    '..KSSSSK..',
    '.KRRRRRRK.',
    '.KRrrrrRK.',
    '.KWWWWWWK.',
    '.KWRRRRWK.',
    '.KWWWWWWK.',
    '.KRrrrrRK.',
    '.KRrrrrRK.',
    '.KRRRRRRK.',
    '.KKKKKKKK.',
    '..SSSSSS..',
    '..KKKKKK..',
  ],
};

// === 6. ZERO POP — silver can w/ red band ==================================
const ZEROPOP_SHELF: SpriteDef = {
  id: 'zeropop-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#3a3a44',
    G: '#7a7a88', // dark silver
    g: '#cdd2da', // bright silver
    R: '#c2122a',
    r: '#ff4655',
  },
  rows: [
    '........................',
    '........................',
    '........KKKKKKKK........',
    '........KSSSSSSK........',
    '.......KSSSSSSSSK.......',
    '.......KSKKKKKKSK.......',
    '......KGGGGGGGGGGK......',
    '......KGggggggggGK......',
    '......KGggggggggGK......',
    '......KGggggggggGK......',
    '......KRRRRRRRRRRK......',
    '......KRrWrWrWrrRK......',
    '......KRrWrWrWrrRK......',
    '......KRRRRRRRRRRK......',
    '......KGggggggggGK......',
    '......KGggWWWWggGK......',
    '......KGgWggggWgGK......',
    '......KGgWgKKgWgGK......',
    '......KGgWggggWgGK......',
    '......KGggWWWWggGK......',
    '......KGggggggggGK......',
    '......KGggggggggGK......',
    '......KGGGGGGGGGGK......',
    '......KKKKKKKKKKKK......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........SSSSSSSS........',
    '........SSSSSSSS........',
    '........KKKKKKKK........',
    '........................',
    '........................',
    '........................',
  ],
};

const ZEROPOP_HAND: SpriteDef = {
  id: 'zeropop-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#3a3a44',
    G: '#7a7a88',
    g: '#cdd2da',
    R: '#c2122a',
    r: '#ff4655',
  },
  rows: [
    '..........',
    '..KKKKKK..',
    '..KSSSSK..',
    '.KGGGGGGK.',
    '.KGggggGK.',
    '.KRRRRRRK.',
    '.KRrrrrRK.',
    '.KRRRRRRK.',
    '.KGggggGK.',
    '.KGggggGK.',
    '.KGGGGGGK.',
    '.KKKKKKKK.',
    '..SSSSSS..',
    '..KKKKKK..',
  ],
};

// === 7. FIZZ — orange can w/ pixel orange-slice motif ======================
const FIZZ_SHELF: SpriteDef = {
  id: 'fizz-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#4a2008',
    O: '#c25a08', // dark orange
    o: '#ff8c00', // bright orange
    Y: '#ffd060', // pale orange-yellow
  },
  rows: [
    '........................',
    '........................',
    '........KKKKKKKK........',
    '........KSSSSSSK........',
    '.......KSSSSSSSSK.......',
    '.......KSKKKKKKSK.......',
    '......KOOOOOOOOOOK......',
    '......KOoooooooooK......',
    '......KOoWWWWWWoOK......',
    '......KOoWooooWoOK......',
    '......KOoWWWWWWoOK......',
    '......KOoooooooOK.......',
    '......KOooooooooOK......',
    '......KOooKKKKooOK......',
    '......KOoKYYYYKoOK......',
    '......KOKYoYYoYKOK......',
    '......KOKYoYYoYKOK......',
    '......KOKYYYYYYKOK......',
    '......KOKYoYYoYKOK......',
    '......KOKYoYYoYKOK......',
    '......KOoKYYYYKoOK......',
    '......KOooKKKKooOK......',
    '......KOooooooooOK......',
    '......KOooooooooOK......',
    '......KOOOOOOOOOOK......',
    '......KKKKKKKKKKKK......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........SSSSSSSS........',
    '........KKKKKKKK........',
    '........................',
    '........................',
  ],
};

const FIZZ_HAND: SpriteDef = {
  id: 'fizz-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#4a2008',
    O: '#c25a08',
    o: '#ff8c00',
    Y: '#ffd060',
  },
  rows: [
    '..........',
    '..KKKKKK..',
    '..KSSSSK..',
    '.KOOOOOOK.',
    '.KOoooooK.',
    '.KOoKYYoK.',
    '.KOYoYYYK.',
    '.KOKYYoOK.',
    '.KOYoYYYK.',
    '.KOoKYYoK.',
    '.KOoooooK.',
    '.KOOOOOOK.',
    '.KKKKKKKK.',
    '..SSSSSS..',
  ],
};

// === 8. CHIP STIX — yellow foil bag w/ chip silhouette =====================
// Bag: crinkled top (alternating K/y), wider top, narrower bottom.
const CHIPSTIX_SHELF: SpriteDef = {
  id: 'chipstix-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#3a3408',
    Y: '#c2b008', // dark yellow
    y: '#ffe600', // bright yellow
    O: '#d28030', // dark chip
    o: '#ffa850', // light chip
  },
  rows: [
    '........................',
    '....K.K.K.K.K.K.K.K.....',
    '...KyKyKyKyKyKyKyKy.....',
    '..KyyyyyyyyyyyyyyyyK....',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYyKKKKKKKKKKKKKyYK...',
    '..KYyKWWWWWWWWWWWKyYK...',
    '..KYyKWyKyKyKyKyWKyYK...',
    '..KYyKWyKyKyKyKyWKyYK...',
    '..KYyKWWWWWWWWWWWKyYK...',
    '..KYyKKKKKKKKKKKKKyYK...',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYyyyyyyKKKKyyyyyYK...',
    '..KYyyyKKKOOOOKKyyyYK...',
    '..KYyKKOOOoooooOKKyYK...',
    '..KYyKOoooooooooKKyYK...',
    '..KYyKOoooKKKoooOKyYK...',
    '..KYyKOoKKKKKKooOKyYK...',
    '..KYyKOoooooooooOKyYK...',
    '..KYyKKOoooooooOKKyYK...',
    '..KYyyKKOOOOOOOKKyyYK...',
    '..KYyyyyKKKKKKKyyyyYK...',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYyyyyyyyyyyyyyyyYK...',
    '..KYYyyyyyyyyyyyyyYYK...',
    '..KKYYYYYYYYYYYYYYYKK...',
    '...KKKKKKKKKKKKKKKKK....',
    '......KSSSSSSSSSK.......',
  ],
};

const CHIPSTIX_HAND: SpriteDef = {
  id: 'chipstix-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    Y: '#c2b008',
    y: '#ffe600',
    O: '#d28030',
    o: '#ffa850',
  },
  rows: [
    'KyKyKyKyKy',
    'KyyyyyyyyK',
    'KYyyyyyyYK',
    'KYyyKKyyYK',
    'KYyKOOKyYK',
    'KYKOoooKYK',
    'KYKOoKoOYK',
    'KYKOoooKYK',
    'KYKKOOKKYK',
    'KYyyKKyyYK',
    'KYyyyyyyYK',
    'KYyyyyyyYK',
    'KYYyyyyYYK',
    'KKKYYYYKKK',
  ],
};

// === 9. MUNCH — red bag, pixel teeth-marks motif ===========================
const MUNCH_SHELF: SpriteDef = {
  id: 'munch-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#3a0408',
    R: '#a8081a', // dark red
    r: '#ff2c9f', // pink-red
    P: '#ff6cb0', // bright pink
  },
  rows: [
    '........................',
    '....K.K.K.K.K.K.K.K.....',
    '...KrKrKrKrKrKrKrKr.....',
    '..KrrrrrrrrrrrrrrrrK....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRrKKKKKKKKKKKKKrRK...',
    '..KRrKWWWWWWWWWWWKrRK...',
    '..KRrKWrrrKrrrKrrWKrRK..',
    '..KRrKWrKrKrKrKrrWKrRK..',
    '..KRrKWWWWWWWWWWWKrRK...',
    '..KRrKKKKKKKKKKKKKrRK...',
    '..KRrrrrPPPPPPrrrrRK....',
    '..KRrrPPWWWWWWPPrrRK....',
    '..KRrPPWWKKKKWWPPrRK....',
    '..KRrPWWKWWWWKWWPRK.....',
    '..KRrPWKWWWWWWKWPRK.....',
    '..KRrPWWKWWWWKWWPRK.....',
    '..KRrPWWWKKKKWWWPRK.....',
    '..KRrPPWWWWWWWWPPRK.....',
    '..KRrrPPWWWWWWPPrRK.....',
    '..KRrrrPPPPPPPPrrRK.....',
    '..KRrrrrrrrrrrrrrRK.....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRrrrrrrrrrrrrrrRK....',
    '..KRRrrrrrrrrrrrrRRK....',
    '..KKRRRRRRRRRRRRRRKK....',
    '...KKKKKKKKKKKKKKKKK....',
  ],
};

const MUNCH_HAND: SpriteDef = {
  id: 'munch-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    R: '#a8081a',
    r: '#ff2c9f',
    P: '#ff6cb0',
    W: '#f5e8ff',
  },
  rows: [
    'KrKrKrKrKr',
    'KrrrrrrrrK',
    'KRrrrrrrRK',
    'KRrKKKKrRK',
    'KRKWWWWKRK',
    'KRKWrrWKRK',
    'KRKWWWWKRK',
    'KRrPPPPrRK',
    'KRrPKKPrRK',
    'KRrPKKPrRK',
    'KRrPPPPrRK',
    'KRrrrrrrRK',
    'KRRrrrrRRK',
    'KKKRRRRKKK',
  ],
};

// === 10. ZAPS — blue bag w/ pixel lightning ================================
const ZAPS_SHELF: SpriteDef = {
  id: 'zaps-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#0a2a44',
    B: '#0a4a78',
    b: '#00f0ff',
    Y: '#ffe600',
  },
  rows: [
    '........................',
    '....K.K.K.K.K.K.K.K.....',
    '...KbKbKbKbKbKbKbKb.....',
    '..KbbbbbbbbbbbbbbbbK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbKKKKKKKKKKKKKbBK...',
    '..KBbKWWWWWWWWWWWKbBK...',
    '..KBbKWbYbYbYbYbWKbBK...',
    '..KBbKWYbYbYbYbYWKbBK...',
    '..KBbKWWWWWWWWWWWKbBK...',
    '..KBbKKKKKKKKKKKKKbBK...',
    '..KBbbbbbbbbYYbbbbBK....',
    '..KBbbbbbbbYYYbbbbBK....',
    '..KBbbbbbbYYYbbbbbBK....',
    '..KBbbbbbYYYYYYbbbBK....',
    '..KBbbbbbbbbYYYYbbBK....',
    '..KBbbbbbbbYYYbbbbBK....',
    '..KBbbbbbbYYYbbbbbBK....',
    '..KBbbbbbYYbbbbbbbBK....',
    '..KBbbbbYYbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBbbbbbbbbbbbbbbBK....',
    '..KBBbbbbbbbbbbbbBBK....',
    '..KKBBBBBBBBBBBBBBKK....',
    '...KKKKKKKKKKKKKKKKK....',
  ],
};

const ZAPS_HAND: SpriteDef = {
  id: 'zaps-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    B: '#0a4a78',
    b: '#00f0ff',
    Y: '#ffe600',
    W: '#f5e8ff',
  },
  rows: [
    'KbKbKbKbKb',
    'KbbbbbbbbK',
    'KBbbbbbbBK',
    'KBKWWWWKBK',
    'KBKWbYWKBK',
    'KBKWWWWKBK',
    'KBbbbYYbBK',
    'KBbbYYbbBK',
    'KBbYYbbbBK',
    'KBbYYYYbBK',
    'KBbbYYbbBK',
    'KBbbbbbbBK',
    'KBBbbbbBBK',
    'KKKBBBBKKK',
  ],
};

// === 11. VOLT BAR — purple wrapper, yellow bolt logo =======================
// Horizontal candy bar with crimped ends (top/bottom borders).
const VOLTBAR_SHELF: SpriteDef = {
  id: 'voltbar-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#2a0e4a',
    P: '#3a106a',
    p: '#a85cff',
    Y: '#ffe600',
    L: '#d4a8ff',
  },
  rows: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '..K.K.K.K.K.K.K.K.K.K...',
    '..KSKSKSKSKSKSKSKSKSK...',
    '..KSPPPPPPPPPPPPPPPSK...',
    '..KSPpppppppppppppPSK...',
    '..KSPpWWWWWWWWWWWpPSK...',
    '..KSPpWpLLLLLLLpWpPSK...',
    '..KSPpWWWWWWWWWWWpPSK...',
    '..KSPpppppppppppPSK.....',
    '..KSPpppppYYpppppPSK....',
    '..KSPppppYYYppppPPSK....',
    '..KSPpppYYYpppppPPSK....',
    '..KSPppYYYYYYpppPPSK....',
    '..KSPpppppYYpppppPSK....',
    '..KSPppppYYpppppPPSK....',
    '..KSPpppYYpppppppPSK....',
    '..KSPppYYpppppppPPSK....',
    '..KSPpppppppppppPPSK....',
    '..KSPpWWWWWWWWWWWpPSK...',
    '..KSPpWpYpYpYpYpWpPSK...',
    '..KSPpWWWWWWWWWWWpPSK...',
    '..KSPpppppppppppPSK.....',
    '..KSPPPPPPPPPPPPPPSK....',
    '..KSKSKSKSKSKSKSKSKSK...',
    '..K.K.K.K.K.K.K.K.K.K...',
    '........................',
  ],
};

const VOLTBAR_HAND: SpriteDef = {
  id: 'voltbar-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#2a0e4a',
    P: '#3a106a',
    p: '#a85cff',
    Y: '#ffe600',
  },
  rows: [
    '..........',
    '..........',
    'KSKSKSKSKS',
    'KSPPPPPPSK',
    'KSPpppppSK',
    'KSPpYYppSK',
    'KSPYYpppSK',
    'KSPpYYppSK',
    'KSPpYYppSK',
    'KSPYYpppSK',
    'KSPpppppSK',
    'KSPPPPPPSK',
    'KSKSKSKSKS',
    '..........',
  ],
};

// === 12. BIT CRUNCH — gold wrapper, brown chocolate bar visible at edges ===
const BITCRUNCH_SHELF: SpriteDef = {
  id: 'bitcrunch-shelf',
  width: 24,
  height: 32,
  palette: {
    '.': 'transparent',
    K: '#050009',
    W: '#f5e8ff',
    S: '#3a3408',
    Y: '#c2b008',
    y: '#ffe600',
    B: '#3a1a08', // dark chocolate
    b: '#6a3010', // mid chocolate
    c: '#8a4a18', // light chocolate
  },
  rows: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '..K.K.K.K.K.K.K.K.K.K...',
    '..KSKSKSKSKSKSKSKSKSK...',
    '..KSYYYYYYYYYYYYYYYSK...',
    '..KSYyyyyyyyyyyyyyySK...',
    '..KSYyKKKKKKKKKKKyySK...',
    '..KSYyKBBBBBBBBBKyySK...',
    '..KSYyKBbbbbbbbBKyySK...',
    '..KSYyKBbcccccbBKyySK...',
    '..KSYyKBbcWWWcbBKyySK...',
    '..KSYyKBbcWyWcbBKyySK...',
    '..KSYyKBbcWyWcbBKyySK...',
    '..KSYyKBbcWyWcbBKyySK...',
    '..KSYyKBbcWyWcbBKyySK...',
    '..KSYyKBbcWWWcbBKyySK...',
    '..KSYyKBbcccccbBKyySK...',
    '..KSYyKBbbbbbbbBKyySK...',
    '..KSYyKBBBBBBBBBKyySK...',
    '..KSYyKKKKKKKKKKKyySK...',
    '..KSYyWWWWWWWWWWWyySK...',
    '..KSYyWyKyKyKyKyWyySK...',
    '..KSYyWWWWWWWWWWWyySK...',
    '..KSYYYYYYYYYYYYYYYSK...',
    '..KSKSKSKSKSKSKSKSKSK...',
    '..K.K.K.K.K.K.K.K.K.K...',
    '........................',
  ],
};

const BITCRUNCH_HAND: SpriteDef = {
  id: 'bitcrunch-hand',
  width: 10,
  height: 14,
  palette: {
    '.': 'transparent',
    K: '#050009',
    S: '#3a3408',
    Y: '#c2b008',
    y: '#ffe600',
    B: '#3a1a08',
    b: '#6a3010',
    c: '#8a4a18',
  },
  rows: [
    '..........',
    '..........',
    'KSKSKSKSKS',
    'KSYYYYYYSK',
    'KSYyyyyySK',
    'KSYBBBBYSK',
    'KSYBbbcBSK',
    'KSYBccbBSK',
    'KSYBbbcBSK',
    'KSYBccbBSK',
    'KSYBbbbBSK',
    'KSYYYYYYSK',
    'KSKSKSKSKS',
    '..........',
  ],
};

// ===========================================================================
// SNACK ITEMS — exactly 12, original designs, no real-brand IP
// ===========================================================================

export const SNACK_ITEMS: SnackItem[] = [
  {
    id: 'beast',
    name: 'BEAST RAGE',
    type: 'energy-drink',
    spriteShelf: BEAST_SHELF,
    spriteHandheld: BEAST_HAND,
    accentColor: '#39ff14',
    flavor: 'WAKE UP, FIGHT BACK',
    action: 'drink',
  },
  {
    id: 'volt',
    name: 'VOLT',
    type: 'energy-drink',
    spriteShelf: VOLT_SHELF,
    spriteHandheld: VOLT_HAND,
    accentColor: '#00f0ff',
    flavor: '10000mg CAFFEINE LIE',
    action: 'drink',
  },
  {
    id: 'riot',
    name: 'RIOT',
    type: 'energy-drink',
    spriteShelf: RIOT_SHELF,
    spriteHandheld: RIOT_HAND,
    accentColor: '#ff2c9f',
    flavor: 'START SOMETHING',
    action: 'drink',
  },
  {
    id: 'zap',
    name: 'ZAP',
    type: 'energy-drink',
    spriteShelf: ZAP_SHELF,
    spriteHandheld: ZAP_HAND,
    accentColor: '#a85cff',
    flavor: 'EYES OPEN, HEAD DOWN',
    action: 'drink',
  },
  {
    id: 'pop-cola',
    name: 'POP COLA',
    type: 'soda',
    spriteShelf: POPCOLA_SHELF,
    spriteHandheld: POPCOLA_HAND,
    accentColor: '#ff4655',
    flavor: 'FOR THIRSTY ARCADE KIDS',
    action: 'drink',
  },
  {
    id: 'zero-pop',
    name: 'ZERO POP',
    type: 'soda',
    spriteShelf: ZEROPOP_SHELF,
    spriteHandheld: ZEROPOP_HAND,
    accentColor: '#cdd2da',
    flavor: 'ALL THE FIZZ, NONE OF THE GUILT',
    action: 'drink',
  },
  {
    id: 'fizz-orange',
    name: 'FIZZ',
    type: 'soda',
    spriteShelf: FIZZ_SHELF,
    spriteHandheld: FIZZ_HAND,
    accentColor: '#ff8c00',
    flavor: 'SUNRISE IN A CAN',
    action: 'drink',
  },
  {
    id: 'chip-stix',
    name: 'CHIP STIX',
    type: 'chips',
    spriteShelf: CHIPSTIX_SHELF,
    spriteHandheld: CHIPSTIX_HAND,
    accentColor: '#ffe600',
    flavor: 'CRUNCHIEST PIXEL IN TOWN',
    action: 'eat',
  },
  {
    id: 'munch',
    name: 'MUNCH',
    type: 'chips',
    spriteShelf: MUNCH_SHELF,
    spriteHandheld: MUNCH_HAND,
    accentColor: '#ff2c9f',
    flavor: 'BITE-SIZED GLORY',
    action: 'eat',
  },
  {
    id: 'zaps',
    name: 'ZAPS',
    type: 'chips',
    spriteShelf: ZAPS_SHELF,
    spriteHandheld: ZAPS_HAND,
    accentColor: '#00f0ff',
    flavor: 'SHOCKING FLAVOR',
    action: 'eat',
  },
  {
    id: 'volt-bar',
    name: 'VOLT BAR',
    type: 'candy',
    spriteShelf: VOLTBAR_SHELF,
    spriteHandheld: VOLTBAR_HAND,
    accentColor: '#a85cff',
    flavor: 'SUGAR + CAFFEINE = WIN',
    action: 'eat',
  },
  {
    id: 'bit-crunch',
    name: 'BIT CRUNCH',
    type: 'candy',
    spriteShelf: BITCRUNCH_SHELF,
    spriteHandheld: BITCRUNCH_HAND,
    accentColor: '#ffe600',
    flavor: '8-BIT CHOCOLATE',
    action: 'eat',
  },
];

/** Lookup helpers */
export const SNACK_BY_ID: Record<string, SnackItem> = Object.fromEntries(
  SNACK_ITEMS.map((s) => [s.id, s]),
);

export function snackById(id: string): SnackItem | undefined {
  return SNACK_BY_ID[id];
}
